### ISSUE TITLE
Decrease minSdk?

### ISSUE THREAD

**Issue by kashifo** [gsurrel/FacebookNotifications#11]
i am editing the code, shall i decrease the minSdk. 
why is that 17? 
is not 14 enough?

**Comment by gsurrel** [comment]
I tried to the lowest possible and still keep it compiling.
A very quick check on my side raises errors in UpdateService on lines 102, 110, 112, 114, 172, 189, 201, 203, 205 and a few more.

Using the support library may/will help but I currently decided not to use it as I wanted to keep the app small.

**Comment by kashifo** [comment]
Okay dude

**Comment by gsurrel** [comment]
I keep the issue open because it's interesting to try to support a lower API level.

**Comment by kashifo** [comment]
Ok, i've implemented new features in my fork, few changes left.
What version code and name shall we assign?

**Comment by kashifo** [comment]
APK size is just 101KB, so it is better to use support library and support more devices.

or

remove new style notification builder, and use old deprecated style notification.

What should we do?

**Comment by gsurrel** [comment]
I'll flag it as `invalid` for now: I want to keep the APK as small as possible as it's not doing much and for sure less than 1MB.

OK for lowering the API level if the downgrades in features are not too significant.
