### ISSUE TITLE
Simplify preferences screen

### ISSUE THREAD

**Issue by gsurrel** [gsurrel/FacebookNotifications#13]
Is there the option of having "no sound" in the sound selector for notifications? If so, it's redundant with the option of enabling/disabling the sound. (I have it on mine but I don't know if it's stock Android)

**Comment by gsurrel** [comment]
Tried to remove the preference for enabling/disabling sound, leaving only the picker.

**Comment by kashifo** [comment]
It's not redundant, keep it back. because there will be long list of ringtones in picker, every time the user has to pick his favorite ringtone to enable / disable ringtones.

the picker will save user's favorite ringtone.

the checkbox will turn on/off sound temporarily or permanently **without having to select ringtone again**

**It was related to me, why did you close before i reply.**

**Comment by gsurrel** [comment]
Yes, there may be a long list of ringtones, but the "None" is always at the top of the list, next to "Default" one. I open this issue for all Android users, to check if this option exists everywhere, which is the case.

What happens for the user if he enabled the sound notification but hears nothing? It seems to be a bug, but it is because he muted them twice: once with the checkbox, once with the "None" ringtone. I have checked my apps and the vast majority offer only the ringtone picker (K9 Mail, Conversations, Google Hangouts to name a few).

I want to keep the app as simple and lean as possible without decreasing the functionalities and the current setup is OK for that. The only drawback is for persons changing the ringtone several times a day. It's for the very same reason that I do not plan to add a user-defined vibration pattern, except if I get a lot of request to be able to customize it.

As [Einstein may have said](http://quoteinvestigator.com/2011/05/13/einstein-simple/), _everything should be made as simple as possible, but no simpler_.

EDIT: I must say that I appreciate a lot your contribution as it is solving some opened issues without overhead. Thanks!

**Comment by kashifo** [comment]
Cool dude, no need of such a big reply.

**Comment by gsurrel** [comment]
I just wanted not to seem harsh, so I carefully explained everything :)

**Comment by kashifo** [comment]
good
