### ISSUE TITLE
allow disabling vibration

### ISSUE THREAD

**Issue by lachlan-00** [gsurrel/FacebookNotifications#15]
I only put vibrate on calls so it would be good to be able to disable vibration on this as well.

**Comment by gsurrel** [comment]
I was expecting it coming :)
It will be done for the next release.

**Comment by lachlan-00** [comment]
Haha, live in fear no more. Everything else is great.

**Comment by gsurrel** [comment]
This has been added in the newest version, where one can choose the vibration pattern.
