### ISSUE TITLE
Add LED Blink Rate Customization

### ISSUE THREAD

**Issue by landry314** [gsurrel/FacebookNotifications#17]
I have run into a problem using this app. If I get a few important notifications from messaging apps with a high LED notification blink rate but then the most recent notification I got was from Notifications for Facebook then the blink rate is overridden and becomes slow even though I have important messages from before. I need to quickly glance at my phone to check for messages but with such a slow blink rate it is easy to miss!

Can you please add blink rate customization? While you are at it an LED color choice would be great too!

Thank you!

**Comment by gsurrel** [comment]
I'll work on that, OK. I think I'll add the same kind of customization for the LED as the one available for the vibration.

**Comment by gsurrel** [comment]
It should be OK, I'll publish it soon. I'm doing some more testing before releasing.

**Comment by gsurrel** [comment]
I've pushed it online. If you don't want to wait for the F-Droid/Play Store update, you can download the .apk in the repository: https://github.com/gsurrel/FacebookNotifications
