### ISSUE TITLE
disable synchronization not working

### ISSUE THREAD

**Issue by Isgar** [gsurrel/FacebookNotifications#20]
I disabled synchronization in the settings menu because it was behaving weirdly, but it seems to have no effect. It is still notifying me of new messages.

Rebooting didnt help.

**Comment by hirvinen** [comment]
I think this should be fixed in #23

**Comment by gsurrel** [comment]
I think so, I'll close it for now, reopen it if you don't see the expected behavior. Thanks @hirvinen for the patch.
