### ISSUE TITLE
Choose version of Facebook site?

### ISSUE THREAD

**Issue by hirvinen** [gsurrel/FacebookNotifications#25]
How about allowing user to choose which version of the Facebook site is shown? Full version probably wouldn't make sense, except maybe on a tablet, but touch.facebook.com offers some advantages over m.facebook.com in terms of UX. Then again it would require javascript to be enabled, but that could be disabled again when navigating outside of facebook.

**Comment by gsurrel** [comment]
I actually had a request for that before. I started to implement it but as soon as it looks like a full browser, users expect more and more features (upload files, back/forward, refresh, share, save images, block images load on cellular network…). As it is not the main objective of the application, I stepped back to just have a simple display.

If you want to use a nice FB wrapper, I'm currently using [SlimSocial for Facebook](https://f-droid.org/repository/browse/?fdfilter=SlimSOcial&fdid=it.rignanese.leo.slimfacebook) which plays nicely with my app.
