### ISSUE TITLE
can't zoom on event description

### ISSUE THREAD

**Issue by J-Hill-Dev** [gsurrel/FacebookNotifications#37]
when viewing a fb event, the text goes beyond the visible area; you have to scroll right then back left to keep reading. rotation of the screen only makes the text bigger.

**Comment by gsurrel** [comment]
I have checked on several different events and I can't reproduce this problem. I would say it's either (or both) a Facebook problem with their mobile website (m.facebook.com) and/or a problem with the webview version installed on your device.

Maybe [installing/updating Android Webview](https://play.google.com/store/apps/details?id=com.google.android.webview) could help, but I'm not sure.
