### ISSUE TITLE
Allow alternate upload types in messages

### ISSUE THREAD

**Issue by snowsquizy** [gsurrel/FacebookNotifications#38]
Currently you are only able to upload JPG to attach to messages.   This should be expanded to include videos and files

**Comment by gsurrel** [comment]
Thanks for the issue, but I fear that is actually a Facebook problem.

Could you please try (using a desktop browser using "https://m.facebook.com") to upload something else than an image and tell me is you can?

Depending on the result, I will try to see what I can do.

**Comment by snowsquizy** [comment]
The website allows you to select alternate file types however they fail to upload with an error presented.

**Comment by gsurrel** [comment]
OK, I have the very same behavior.

I guess I'll close the issue until Facebook updates their simple mobile website to allow any kind of file to be uploaded. Sorry I can't help you 😞
