### ISSUE TITLE
Keep versioncode updated

### ISSUE THREAD

**Issue by ghost** [gsurrel/FacebookNotifications#4]
Note that you "released" different versions with the same versioncode of 1. The VC is an integer that is used to check if an apk is an update to an app or not. Please bump the VC when you release new versions. See https://developer.android.com/tools/publishing/versioning.html.

**Comment by gsurrel** [comment]
Thanks for the link, it's now corrected. It's the first time I really publish an app, sorry for the hiccups.

**Comment by ghost** [comment]
Don't worry about that. Release management on Android is somewhat more strict than usual, since the Android system itself enforces certain rules. Even some senior devs screw that up once in a while or some are not even aware of it, since the play-store has features like forcing updates etc.. But in time, you get the hang of it.

Thanks for the quick responses!
