### ISSUE TITLE
[Request] Change update timing

### ISSUE THREAD

**Issue by gsurrel** [gsurrel/FacebookNotifications#6]
It could be nice to be able to change the update frequency rather than have the fixed-time 5 minutes interval.

**Comment by kashifo** [comment]
It's on the way.

**Comment by kashifo** [comment]
Done adding this feature. you can close it now.

**Comment by kashifo** [comment]
review and update as soon as possible.

**Comment by gsurrel** [comment]
Done and published. I changed to a time in minutes to avoid too frequent polling of Facebook, plus the AlarmManager is set to approximate alarms to enable better power saving. The allowed range is from one minute to one week to prevent too heavy input mistakes.

Thanks for your contribution :)

**Comment by kashifo** [comment]
It's my pleasure dude, thank you too.
