### ISSUE TITLE
Support the "back" button

### ISSUE THREAD

**Issue by sm4rk0** [gsurrel/FacebookNotifications#7]
Currently, back button quits the app instead of going back to previos page if there is one.

**Comment by gsurrel** [comment]
Indeed, that's a bug. I did not plan to make the app as a dedicated browser, but I guess not everybody wants to install Tinfoil or FaceSlim so separate Facebook from the main browser.

I'm also thinking about using https://touch.facebook.com instead of https://m.facebook.com so it's nicer for the user-experience.

**Comment by sm4rk0** [comment]
Re: dedicated browser
What do you think about an option to open the links with other browsers?
Or tap-and-hold to copy/share the link?
Then no navigation from the notifications page would be necessary/possible.

Re: touch interface
Yes, that should look better. Did you consider directly opening the notifications page?
https://touch.facebook.com/?soft=notifications

Thanks!

**Comment by gsurrel** [comment]
As clicking from the notification just asks Android to browse to facebook, it should show the dialog "Choose the application to continue the action", so a standard browser can be chosen (I've chosen Tinfoil for Facebook). 

Taping the notification opens the most specific link:
- If you have only friends requests, it opens `https://m.facebook.com/friends/center/requests/`
- If you have only messages, it opens `https://m.facebook.com/messages/`
- If you have only notifications, it opens `https://m.facebook.com/notifications.php`
- If you have a combination of the above, it opens `https://m.facebook.com/` with additional buttons to open more specific pages

If you have another behavior, could you please tell me, I've not noticed any malfunctions in this process.

**Comment by sm4rk0** [comment]
You're right. First I've chosen [WebApps](https://github.com/tobykurien/WebApps), but if you've disabled third-party requests (except for white-listed ones, saved per web app) it doesn't work smoothly when opened externally (from a link) vs. opening a web app directly. So, I switched back to FacebookNotifications as the default app.

The scenario I proposed would be:
1. tapping the notification
2. FacebookNotifications opens
3. any subsequent link in the app opens the "Choose the application to continue the action" dialog
But I'm not sure if it's feasible or possible at all...

**Comment by gsurrel** [comment]
I don't see the benefit of the workflow you suggest compared to starting directly with "3".

Also, I have not heard of WebApps so I'm not sure to understand exactly what is the problem: when you open a Facebook link, you are always redirected to the main page of the website and not to the more specific link? (I mean, loading test.com/deep/link.html loads simply test.com)?

**Comment by sm4rk0** [comment]
Sorry for this digression. I figured that the workflow I suggested is actually a workaround for WebApps' misbehaviour. Please disregard this.

The problem is that when the page is opened "externally" in WebApps, 3rd party domains are disabled, so Facebook is opened without resources from fbcdn.net and akamaihd.net which makes it unusable until the domains are manually unblocked.

**Comment by gsurrel** [comment]
The "back" button handling has been added.
