### ISSUE TITLE
[Request] Notification sound

### ISSUE THREAD

**Issue by sm4rk0** [gsurrel/FacebookNotifications#8]
How about adding an option:
- no sound
- default notification
- custom sound

**Comment by gsurrel** [comment]
I'll implement that when I'll have time to work on the app again, along with the others issues. It's not too hard to implement, I guess: I just need to provide much more options for the users with a more complete settings page.

**Comment by kashifo** [comment]
@gsurrel shall i do it?

**Comment by gsurrel** [comment]
@KashifAnwaar If you want to, you are very welcome :)

**Comment by kashifo** [comment]
@gsurrel Wow, i didn't expect reply so soon

**Comment by gsurrel** [comment]
I guess it can rise to version name 1.6.0, and simple version code incrementation for the version code. I'll check on the merge and test it locally before pushing on master on github.

**Comment by kashifo** [comment]
sure

**Comment by kashifo** [comment]
don't push yourself, i'll create pull request

**Comment by gsurrel** [comment]
Added along with per-notification configuration
