### ISSUE TITLE
Regarding user agent

### ISSUE THREAD

**Issue by nwhr** [gsurrel/FacebookNotifications#9]
Hello, this looks like an awesome app, thank you very much.
Just one little question. Since my default user agent shows device and build info and this app gets facebook notifications from m.facebook.com, I'm wondering if it uses the same UA string as my browser. There are some user agent switchers on the Play Store but they are just for Chrome, so I don't know what else to do other than ask if you can shed some light about it. I really want to hide my device info from UA string. Can you edit it to show some common UA string instead? Thank you mate.

**Comment by gsurrel** [comment]
The app always uses a [custom user-agent](https://github.com/gsurrel/FacebookNotifications/blob/master/app/src/main/java/org/surrel/facebooknotifications/MainActivity.java): the app name.

If you open the [Facebook security settings](https://www.facebook.com/settings?tab=security&section=sessions&view), you can see the sessions opened to your account. The app currently shows up as "Device type: Unknown" and when hovering the **[?]**, it shows "Facebook Notifications". I don't know it they can guess what kind of device it is using with other metadata, though.
